// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYNd2iNDp-gfxRvq5iLr_z-_RsBQRVUGA',
    appId: '1:506443610589:web:30154719a073f1f3609e34',
    messagingSenderId: '506443610589',
    projectId: 'appsoraku',
    authDomain: 'appsoraku.firebaseapp.com',
    databaseURL:
        'https://appsoraku-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appsoraku.firebasestorage.app',
    measurementId: 'G-Y5TB7WK9M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuxKC-z90Z9F5XoTDkub8qoYHK2DctQUo',
    appId: '1:506443610589:android:f15b4a35e5f4ef3b609e34',
    messagingSenderId: '506443610589',
    projectId: 'appsoraku',
    databaseURL:
        'https://appsoraku-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appsoraku.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXefHFA96vf0ICPbt9H0rfxn68hsmM7nY',
    appId: '1:506443610589:ios:2618321da6ae8a16609e34',
    messagingSenderId: '506443610589',
    projectId: 'appsoraku',
    databaseURL:
        'https://appsoraku-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appsoraku.firebasestorage.app',
    iosBundleId: 'com.soraku.sorami',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXefHFA96vf0ICPbt9H0rfxn68hsmM7nY',
    appId: '1:506443610589:ios:675e7f08a458329b609e34',
    messagingSenderId: '506443610589',
    projectId: 'appsoraku',
    databaseURL:
        'https://appsoraku-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appsoraku.firebasestorage.app',
    iosBundleId: 'com.soraku.sorami',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1HPuvHhE--wzwJ1tDHxmQo_U7fQVQvFU',
    appId: '1:506443610589:web:483009ba7c53512a609e34',
    messagingSenderId: '506443610589',
    projectId: 'appsoraku',
    authDomain: 'appsoraku.firebaseapp.com',
    databaseURL:
        'https://appsoraku-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appsoraku.firebasestorage.app',
    measurementId: 'G-C1P78J9SVF',
  );
}
